image: node:8

cache:
  paths:
    # - node_modules

pages:
  script:
    - npm install
    - node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - master
